### ISSUE TITLE
Minor comments

### ISSUE THREAD

**Issue by eddelbuettel** [ess-intro/presentation-ess-from-spacemacs#1]
Fabulous!  Thanks for starting this.  It is a topic where many of us, myself included, will learn something new!

Some random thoughI had based on something I used with per-student repos is to maybe prefix all 'talks' repos with a common handle.  Ideas or or preference?  Is 'talk-ess-spacemacs' fine or too woody?   It is not quite a problem yet.

Another idea was about the "stylistic" aspects and the "marketing".  I don't think what we do should be _at all_ positioned as something that is better or different or [insert term here] than some other market-leading alternative.  I would much prefer for us to not name other approaches.  This is not an "instead" initiative, it simply an invitation for people to try something they may have been curious about already.   Arguably the one permitted exception would be "emacs vs spaceemacs" or "emacs vs doom" as it is in the same family.  But otherwise I don't think we need to mention any other tools.  Or is that too uptight?

**Comment by aezarebski** [comment]
Good suggestion. I've used the "presentation" prefix, since it is unclear at the moment in case there doesn't end up being an audio component. 

I 100% agree with the stylistic aspect and have changed the readme to hopefully be more friendly. Would you mind reposting that final paragraph in the mailing list please? It seems like a good way to make sure we are all on the same page.

**Comment by eddelbuettel** [comment]
Howdy. Thanks for the name change. And for the thumbs-up on the positioning / marketing.  I don't to be too heavy-handend here as we are all among peers and equal and neither or nor others "own" anything but I did make a similar statement on the collabedit page.

We do need new central resources. I started a little below https://github.com/ess-intro/ess-intro/wiki  Maybe we can add a top-level page 'Style' there?

**Comment by eddelbuettel** [comment]
Ok, I started https://github.com/ess-intro/ess-intro/wiki/Style

**Comment by aezarebski** [comment]
Cool cool, thanks :)

**Comment by eddelbuettel** [comment]
Now you and I "merely" have to get everybody else over here onto GitHub :)

**Comment by aezarebski** [comment]
Urgh, I was thinking removing the collabedit content and just leaving a link to the wiki would encourage people over. But then there is the difficulty of contributing to the wiki, it sounds pretty complicated to edit those things. At the risk of putting more work on your plate, perhaps a "contributing guide" would be useful.

**Comment by eddelbuettel** [comment]
It's definitely _good_ that the collabedit page is "open" to everybody.  It is definitely _bad_ that it is not logged and reversible. I have been taking (two in total, nothing much yet) snapshots and will continue to do so and mark on that page the suggestion to come to the wiki...

Similarly, besides you one (or two?) other expressed interest in talking spacemacs.  Maybe you can reach out to them to pool resources?  This is a topic I am quite excited about because I both know zilch and see this as a good intro to all things One True Editor including ESS :)

**Comment by aezarebski** [comment]
Occasionally copying the collabedit page over to the github is probably a small cost for the ease of use.

Cool about some other spacemacs users, i'll touch base with them to compare notes.
