### ISSUE TITLE
outline for presentation(s)

### ISSUE THREAD

**Issue by aezarebski** [ess-intro/presentation-ess-from-spacemacs#2]
@chr1swallace  would you be interested in brainstorming an outline for the doom/spacemacs presentations here? My outline so far is below:

1. Motivation for spacemacs
2. What ESS looks like from spacemacs
3. How to learn more about spacemacs

If anyone else is interested, input would be very much appreciated.

**Comment by chr1swallace** [comment]
I guess my intended audience was a little limited compared to yours, I imagined focusing just on "Users of R who are interested ESS and who do not necessarily already have emacs experience" but I would say the same outline works either way :)  I might suggest

1. Motivation for doom (opinionated fast-start configuration, vim/emacs keybindings)
2. How setting up ESS differs for doom (I don't know about spacemacs, but doom has its own way of installing packages, and even own version of use-package. I was planning to refer to https://github.com/ess-intro/presentation-ess-base-install and just point out the differences in the install section)
[3. potentially, useful key configs if you are using vim keybindings, ie remapping C-c C-c and friends to something in normal/visual mode]
4 [or 3] How to learn more about doom emacs

?

**Comment by aezarebski** [comment]
Yep, starting with with `base-install` document and just pointing out the differences sounds like a solid approach.

**Comment by aezarebski** [comment]
Hi @chr1swallace , I've sketched out the content I'd like to present which is partially based on the `base-install` notes, but mainly just working through setting up a fresh installation to see what steps were involved. Anyway, it's in `presentation/README.org` if you want to check it out :)
