### ISSUE TITLE
Address helpful comments from Daniel Nicolai

### ISSUE THREAD

**Issue by aezarebski** [ess-intro/presentation-ess-from-spacemacs#3]
The following comments where provided by a Spacemacs user on Gitter.

- [x]  mention that Spacemacs preferably requires learning Emacs or even better Vim keybindings
- [x] Consistent use of "Spacemacs" with a capital 's'
- [x] SPC b d to kill the repl which is easier to remember.
- [x] Add comments about navigating Info in the Gotchas section.

Daniel Nicolai
@dalanicolai
12:59
Hi I will quickly have a look at your document. Don't know the best workflow but I'll start with some comments here
So it seems to me that you could mention that Spacemacs preferably requires learning Emacs or even better Vim keybindings.
Personally I write Emacs and Spacemacs with capitals, but that choice is up to you of course
In the discoverability section you could mention the SPC h d functionality. Where you can find function/variables/mode/keybindings etc. by guessing their names
Alexander E. Zarebski
@aezarebski
13:23
Thanks!
Daniel Nicolai
@dalanicolai
13:23
Yeah still looking at it.. but got interrupted
Alexander E. Zarebski
@aezarebski
13:24
Cheers :)
Daniel Nicolai
@dalanicolai
13:24
Kill the REPL can usally also be done with SPC b d
From normal mode of course
state
I recognize what you are saying about Info mode. I have added J/K keybindings for 'scrolling' through it. Also you can use SPC t k m to get major-mode keybindings in a persistent which-key window. (You should sync, i.e. git pull) with the latest develop branch for that.
I think it might be wise to recommend using the develop branch
https://develop.spacemacs.org/doc/DOCUMENTATION.html#which-key-persistent
Daniel Nicolai
@dalanicolai
13:30
Also evil-collection has been added to Spacemacs. So that you could run M-: (evil-collection-info-setup)
But also I don't know yet which keybindings I prefer there
Alexander E. Zarebski
@aezarebski
13:33
Yer, I came straight to spacemacs, so I don't really have a reference point for emacs vs vim keybindings, I'll have a crack and see if I can improve on that section.
Daniel Nicolai
@dalanicolai
13:34
Haha, well it is not a very important section... but I recommend to use J/K and SPC t k m
Alexander E. Zarebski
@aezarebski
13:34
Hard to know how important navigation of Info pages is now it's so easy to access this stuff via a browser.
Although, if it is easier to navigate that might change for me...
Thanks so much for the suggestions.
Daniel Nicolai
@dalanicolai
13:35
Yeah through, but indeed I prefer the Info nodes. But indeed it should be clear how to navigate there
Alexander E. Zarebski
@aezarebski
13:35
Do you mind if I copy this into an issue on the repo for future reference?
Daniel Nicolai
@dalanicolai
13:35
Haha, I dont know which part you'd like to copy. But you can do with it whatever you like...

**Comment by aezarebski** [comment]
To do a case sensitive find replace of "spacemacs" for "Spacemacs" use the following `:%s/spacemacs/Spacemacs/Igc`, you need to have the `c` command there so that you can skip over instances of "spacemacs" that appear inside URLs.

**Comment by dalanicolai** [comment]
> To do a case sensitive find replace of "spacemacs" for "Spacemacs" use the following `:%s/spacemacs/Spacemacs/Igc`, you need to have the `c` command there so that you can skip over instances of "spacemacs" that appear inside URLs.

Or, equivalently, just use `query-replace-regexp` (`C-M-%`)...

**Comment by aezarebski** [comment]
Of course there is an emacs command for that https://xkcd.com/378/ cheers.
